### PR TITLE
Customer as Resource/ PIP package name

### PR DESCRIPTION
**Pull request by pbassut**
Solves #15 and #13

### CODE REVIEW

**Comment by pbassut** [comment]
Will this be merged?

**Comment by mbodock** [comment]
Just 2 things
* `BASE_URL` should be imported from settings.
* `__init__` should accept `kwargs` and put in `data`, matching future API changes.

I'm really sorry for the late answer, but has been a tough week.

**Comment by pbassut** [comment]
Okay, all set. Let me just rebase now.

**Comment by mbodock** [comment]
Now just merge the `self.data` with `kwargs`.

I'll test 1st thing tomorrow.

**Comment by mbodock** [comment]
@pbassut any news about the `self.data` ?

**Comment by victorgama** [comment]
Fixed by 900edc1 and 7d177e9. Thanks!

**Comment by pbassut** [comment]
Looks like the only thing that was added was a few letters in addition to completely ruling out the work I did. That's discouraging...

**Comment by mbodock** [comment]
Hey @pbassut do you mind finish your PR ?

Please dont take too much to answer.

**Comment by pbassut** [comment]
@mbodock My work was already done by someone else. I can't realize why finishing this PR would be productive.

**Comment by pbassut** [comment]
Woops, looks like this one wasn't done. 
It's on the way now.

**Comment by mbodock** [comment]
The changes have been reverted.

You don't have to. But would be really nice. ;)

**Comment by pbassut** [comment]
It's done.

**Comment by mbodock** [comment]
I'll check.

**Comment by mbodock** [comment]
@pbassut Looks really nice.

Do you mind squash your commits, so the history don't get too polluted?
There's a lot of duplicated commits with meaningless messages.

**Comment by pbassut** [comment]
Let me know what you think

**Comment by mbodock** [comment]
I don't get it, why didn't you squashed the merge commit ?

**Comment by pbassut** [comment]
Sorry, I was leaving work at that time. Kinda a hurry :).
It's done now.

**Comment by mbodock** [comment]
Its looking really fine, just one more thing. In your rebase you probably mess up with the README.
Could you please revert?

**Comment by mbodock** [comment]
Ping @pbassut.

**Comment by pbassut** [comment]
Dame, didn't realize that. Don't worry, I'll fix it.

Enviado do meu iPhone

**Comment by mbodock** [comment]
@pbassut any news ?

**Comment by pbassut** [comment]
Going in now. I'll check on that as soon as I get there 

Enviado do meu iPhone

**Comment by pbassut** [comment]
@mbodock So, I don't see what's wrong with it. 
Why is the README messed up?

**Comment by mbodock** [comment]
the structure of the current README is a little better.
The README isn't messed up, I just prefer the one Victor wrote.

Try let it unmodified.

**Comment by pbassut** [comment]
@mbodock Well, so that's the one victor did. I didn't touch the README in my original PR(just added a line, didn't permutate the lines). That came from the commits/reverses/rebases.
It wasn't me the modified it and my original commit.
Sure you want me to remove them?

**Comment by pbassut** [comment]
[Take a look here](https://github.com/pagarme/pagarme-python/commit/900edc160e4c57337db68c3938f06d26b7756a12)

**Comment by mbodock** [comment]
Your changes [here](https://github.com/pagarme/pagarme-python/pull/17/files) tells that you reversed the README.

**Comment by pbassut** [comment]
We're all good now, I guess.
Let me know about anything.

**Comment by mbodock** [comment]
Thank you @pbassut. I'll talk with the release master when we will make new release.

**Pull request merged**
