### PR TITLE
Add Pagar.Me's partial refund

### PR DESCRIPTION
**Pull request by rodrigoPgSup**

### CODE REVIEW

**Comment by rodrigoPgSup** [comment]
Greetings @mbodock, how are you? 

We intend to implement new features in this awesome Library, and we would love if you could review
some of our PR's. What do you think?

Thank you very much.

**Comment by mbodock** [comment]
Hello @rodrigoPgSup, feel free to create PRs, any contribution is very welcome!
This one specifically I didn't understand the purpose, perhaps you could explain to me.

**Comment by rodrigoPgSup** [comment]
Hi @mbodock , thank you, we appreciated. This one's still being built. We will start with a simple change, that is, include Pagar.Me's partial refund feature at the library. Thank you for your time, see ya at Review!

**Comment by mbodock** [comment]
Hello @rodrigoPgSup, thanks for your interest in our repository.

Next time wait until your feature is complete to open a PR. Or if you **really, really need** any help you can open a PR with a title starting with 'WIP:' wich means "working in progress', which you'll change later.

So you avoid unnecessary work of everyone watching the repository.

I hope see your new features soon.

Regards

**Pull request closed without merging**
